version: "3.9"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps the container port 3000 to host port 3000
    volumes:
      - .:/app # Syncs the local app directory with the container
      - /app/node_modules # Avoids syncing node_modules
    environment:
      - NODE_ENV=production
